CREATE TABLE offices
(
    office_id NUMBER NOT NULL,

    city VARCHAR2(50) NOT NULL,

    address VARCHAR2(200),

    CONSTRAINT pk_offices
        PRIMARY KEY (office_id),

    CONSTRAINT uq_office_city
        UNIQUE(city)
);

CREATE TABLE app_users (
    user_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    full_name VARCHAR2(100) NOT NULL,
    email VARCHAR2(255) NOT NULL,
    role_code VARCHAR2(20) NOT NULL,
    line_manager_id NUMBER,
    is_active NUMBER(1) DEFAULT 1 NOT NULL,
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    office_id NUMBER NOT NULL,

	CONSTRAINT fk_user_office
	FOREIGN KEY (office_id)
	REFERENCES offices(office_id),
    

    CONSTRAINT pk_app_users
        PRIMARY KEY (user_id),

    CONSTRAINT uq_app_users_email
        UNIQUE (email),

    CONSTRAINT chk_app_users_role
        CHECK (role_code IN ('EMPLOYEE', 'LINE_MANAGER', 'HR', 'ADMIN')),

    CONSTRAINT chk_app_users_active
        CHECK (is_active IN (0, 1)),

    CONSTRAINT chk_employee_has_manager
        CHECK (
            role_code <> 'EMPLOYEE'
            OR line_manager_id IS NOT NULL
        ),

    CONSTRAINT fk_app_users_line_manager
        FOREIGN KEY (line_manager_id)
        REFERENCES app_users(user_id)
);

CREATE TABLE timesheets (
    timesheet_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    employee_id NUMBER NOT NULL,
    week_start_date DATE NOT NULL,

    monday_hours NUMBER(4, 2) DEFAULT 0 NOT NULL,
    tuesday_hours NUMBER(4, 2) DEFAULT 0 NOT NULL,
    wednesday_hours NUMBER(4, 2) DEFAULT 0 NOT NULL,
    thursday_hours NUMBER(4, 2) DEFAULT 0 NOT NULL,
    friday_hours NUMBER(4, 2) DEFAULT 0 NOT NULL,

    monday_place VARCHAR2(10) DEFAULT 'REMOTE' NOT NULL,
    tuesday_place VARCHAR2(10) DEFAULT 'REMOTE' NOT NULL,
    wednesday_place VARCHAR2(10) DEFAULT 'REMOTE' NOT NULL,
    thursday_place VARCHAR2(10) DEFAULT 'REMOTE' NOT NULL,
    friday_place VARCHAR2(10) DEFAULT 'REMOTE' NOT NULL,

    status VARCHAR2(20) DEFAULT 'DRAFT' NOT NULL,
    submitted_at TIMESTAMP,
    reviewed_by NUMBER,
    reviewed_at TIMESTAMP,
    rejection_reason VARCHAR2(500),
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,

    work_details CLOB,
    office_id NUMBER NOT NULL,

	CONSTRAINT fk_timesheet_office
	FOREIGN KEY (office_id)
	REFERENCES offices(office_id),

    CONSTRAINT chk_work_details_json
        CHECK (work_details IS JSON),

    CONSTRAINT pk_timesheets
        PRIMARY KEY (timesheet_id),

    CONSTRAINT uq_timesheets_employee_week
        UNIQUE (employee_id, week_start_date),

    CONSTRAINT fk_timesheets_employee
        FOREIGN KEY (employee_id)
        REFERENCES app_users(user_id),

    CONSTRAINT fk_timesheets_reviewed_by
        FOREIGN KEY (reviewed_by)
        REFERENCES app_users(user_id),

    CONSTRAINT chk_timesheet_status
        CHECK (status IN ('DRAFT', 'SUBMITTED', 'AUTO_REJECTED', 'APPROVED', 'REJECTED')),

    CONSTRAINT chk_timesheet_hours
        CHECK (
            monday_hours BETWEEN 0 AND 24
            AND tuesday_hours BETWEEN 0 AND 24
            AND wednesday_hours BETWEEN 0 AND 24
            AND thursday_hours BETWEEN 0 AND 24
            AND friday_hours BETWEEN 0 AND 24
        ),

    CONSTRAINT chk_timesheet_places
        CHECK (
            monday_place IN ('REMOTE', 'OFFICE')
            AND tuesday_place IN ('REMOTE', 'OFFICE')
            AND wednesday_place IN ('REMOTE', 'OFFICE')
            AND thursday_place IN ('REMOTE', 'OFFICE')
            AND friday_place IN ('REMOTE', 'OFFICE')
        ),

    CONSTRAINT chk_timesheet_review_fields
        CHECK (
            status NOT IN ('APPROVED', 'REJECTED')
            OR (reviewed_by IS NOT NULL AND reviewed_at IS NOT NULL)
        ),

    CONSTRAINT chk_timesheet_rejection_reason
        CHECK (
            status NOT IN ('AUTO_REJECTED', 'REJECTED')
            OR rejection_reason IS NOT NULL
        )
)PARTITION BY LIST (office_id)
(
    PARTITION p_bucharest VALUES (1),

    PARTITION p_brasov VALUES (2),

    PARTITION p_cluj VALUES (3),

    PARTITION p_iasi VALUES (4),

    PARTITION p_pitesti VALUES (5),

    PARTITION p_suceava VALUES (6),

    PARTITION p_targu_mures VALUES (7),

    PARTITION p_timisoara VALUES (8)
);

CREATE INDEX idx_app_users_line_manager
    ON app_users(line_manager_id);

CREATE INDEX idx_timesheets_employee
    ON timesheets(employee_id);

CREATE INDEX idx_timesheets_status
    ON timesheets(status);

CREATE INDEX idx_timesheets_week_start
    ON timesheets(week_start_date);

CREATE INDEX idx_users_office
    ON app_users(office_id);



CREATE OR REPLACE PROCEDURE submit_timesheet (
    p_timesheet_id IN timesheets.timesheet_id%TYPE,
    p_employee_id IN app_users.user_id%TYPE
)
IS
    v_count NUMBER;
BEGIN
    -- Checks whether the specified timesheet belongs to the employee and can be submitted.
    -- Checks that the submitted timesheet belongs to an active line manager.
    -- Checks that the submitted timesheet belongs to an active line manager.

    -- Counts eligible timesheets belonging to the specified employee.
    SELECT COUNT(*)
    INTO v_count
    FROM timesheets
    WHERE timesheet_id = p_timesheet_id
      AND employee_id = p_employee_id
      AND status IN ('DRAFT', 'AUTO_REJECTED', 'REJECTED');

    IF v_count = 0 THEN
        RAISE_APPLICATION_ERROR(
            -20001,
            'Timesheet does not belong to this employee or cannot be submitted.'
        );
    END IF;

    UPDATE timesheets
    SET status = 'SUBMITTED'
    WHERE timesheet_id = p_timesheet_id;
END;
/

CREATE OR REPLACE PROCEDURE reject_timesheet (
    p_timesheet_id IN timesheets.timesheet_id%TYPE,
    p_manager_id IN app_users.user_id%TYPE,
    p_rejection_reason IN timesheets.rejection_reason%TYPE
)
IS
    v_count NUMBER;
BEGIN
    IF p_rejection_reason IS NULL THEN
        RAISE_APPLICATION_ERROR(-20003, 'A rejection reason is required.');
    END IF;

    -- Verifies that the timesheet is submitted, belongs to the manager's employee,
    -- and that the manager is an active line manager.
    SELECT COUNT(*)
    INTO v_count
    FROM timesheets t
    JOIN app_users employee
        ON employee.user_id = t.employee_id
    JOIN app_users manager_user
        ON manager_user.user_id = p_manager_id
    WHERE t.timesheet_id = p_timesheet_id
      AND t.status = 'SUBMITTED'
      AND employee.line_manager_id = p_manager_id
      AND manager_user.role_code = 'LINE_MANAGER'
      AND manager_user.is_active = 1;

    IF v_count = 0 THEN
        RAISE_APPLICATION_ERROR(
            -20004,
            'Timesheet is not submitted or does not belong to this line manager.'
        );
    END IF;

    UPDATE timesheets
    SET status = 'REJECTED',
        reviewed_by = p_manager_id,
        reviewed_at = SYSTIMESTAMP,
        rejection_reason = p_rejection_reason
    WHERE timesheet_id = p_timesheet_id;
END;
/

CREATE OR REPLACE PROCEDURE approve_timesheet (
    p_timesheet_id IN timesheets.timesheet_id%TYPE,
    p_manager_id IN app_users.user_id%TYPE
)
IS
    v_count NUMBER;
BEGIN
    -- Verifies that the submitted timesheet belongs to an employee managed
    -- by the specified active line manager.
    SELECT COUNT(*)
    INTO v_count
    FROM timesheets t
    JOIN app_users employee
        ON employee.user_id = t.employee_id
    JOIN app_users manager_user
        ON manager_user.user_id = p_manager_id
    WHERE t.timesheet_id = p_timesheet_id
      AND t.status = 'SUBMITTED'
      AND employee.line_manager_id = p_manager_id
      AND manager_user.role_code = 'LINE_MANAGER'
      AND manager_user.is_active = 1;

    IF v_count = 0 THEN
        RAISE_APPLICATION_ERROR(
            -20002,
            'Timesheet is not submitted or does not belong to this line manager.'
        );
    END IF;

    UPDATE timesheets
    SET status = 'APPROVED',
        reviewed_by = p_manager_id,
        reviewed_at = SYSTIMESTAMP,
        rejection_reason = NULL
    WHERE timesheet_id = p_timesheet_id;
END;
/


CREATE OR REPLACE VIEW v_timesheet_overview AS
SELECT
    t.timesheet_id,
    t.employee_id,
    employee.full_name AS employee_name,
    employee.email AS employee_email,
    employee.line_manager_id,
    manager_user.full_name AS line_manager_name,
    t.week_start_date,
    t.status,
    (
          t.monday_hours
        + t.tuesday_hours
        + t.wednesday_hours
        + t.thursday_hours
        + t.friday_hours
    ) AS total_hours,
    (
          CASE WHEN t.monday_place = 'OFFICE' AND t.monday_hours > 0 THEN 1 ELSE 0 END
        + CASE WHEN t.tuesday_place = 'OFFICE' AND t.tuesday_hours > 0 THEN 1 ELSE 0 END
        + CASE WHEN t.wednesday_place = 'OFFICE' AND t.wednesday_hours > 0 THEN 1 ELSE 0 END
        + CASE WHEN t.thursday_place = 'OFFICE' AND t.thursday_hours > 0 THEN 1 ELSE 0 END
        + CASE WHEN t.friday_place = 'OFFICE' AND t.friday_hours > 0 THEN 1 ELSE 0 END
    ) AS office_days,
    t.submitted_at,
    t.reviewed_by,
    reviewer.full_name AS reviewed_by_name,
    o.city,
    t.reviewed_at,
    t.rejection_reason
FROM timesheets t
JOIN app_users employee
    ON employee.user_id = t.employee_id
JOIN offices o
    ON o.office_id = employee.office_id
LEFT JOIN app_users manager_user
    ON manager_user.user_id = employee.line_manager_id
LEFT JOIN app_users reviewer
    ON reviewer.user_id = t.reviewed_by;


CREATE MATERIALIZED VIEW mv_employee_weekly_hours
BUILD IMMEDIATE
REFRESH COMPLETE ON DEMAND
AS
SELECT
    employee_id,
    COUNT(*) AS total_timesheets,
    SUM(
          monday_hours
        + tuesday_hours
        + wednesday_hours
        + thursday_hours
        + friday_hours
    ) AS total_hours
FROM timesheets
GROUP BY employee_id;


-- Displays the total approved working hours for every employee.
SELECT
    employee_id,
    SUM(
          monday_hours
        + tuesday_hours
        + wednesday_hours
        + thursday_hours
        + friday_hours
    ) AS total_hours
FROM timesheets
WHERE status = 'APPROVED'
GROUP BY employee_id;

-- Lists every employee together with their line manager.
-- Employees without a manager are also displayed.
SELECT
    e.full_name AS employee_name,
    m.full_name AS manager_name
FROM app_users e
LEFT JOIN app_users m
    ON e.line_manager_id = m.user_id;


-- Ranks employees by their total approved worked hours.
SELECT
    employee_id,
    SUM(
          monday_hours
        + tuesday_hours
        + wednesday_hours
        + thursday_hours
        + friday_hours
    ) AS total_hours,
    RANK() OVER (
        ORDER BY SUM(
              monday_hours
            + tuesday_hours
            + wednesday_hours
            + thursday_hours
            + friday_hours
        ) DESC
    ) AS employee_rank
FROM timesheets
WHERE status = 'APPROVED'
GROUP BY employee_id;
