
---------------------------------------------------------------------------------
---------------------------- PART I ---------------------------------------------
---------------------------------------------------------------------------------

------------------------
-- 1. Logging Table
------------------------

CREATE TABLE debug_log (
    log_id       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    log_time     TIMESTAMP DEFAULT SYSTIMESTAMP,
    module_name  VARCHAR2(100),
    line_no      NUMBER,
    log_level    VARCHAR2(10) DEFAULT 'INFO' NOT NULL,
    log_message  VARCHAR2(4000),
    session_id   VARCHAR2(50) DEFAULT SYS_CONTEXT('USERENV', 'SESSIONID'),
    CONSTRAINT chk_debug_log_level
        CHECK (log_level IN ('DEBUG', 'INFO', 'WARN', 'ERROR'))
);

------------------------
-- 2. Utility package
------------------------

CREATE OR REPLACE PACKAGE debug_utils AS
    g_debug_mode BOOLEAN := FALSE;

    PROCEDURE enable_debug;
    PROCEDURE disable_debug;
    PROCEDURE enable_level(p_level VARCHAR2);
    PROCEDURE disable_level(p_level VARCHAR2);

    PROCEDURE log(
        p_module_name VARCHAR2,
        p_line        NUMBER,
        p_message     VARCHAR2,
        p_level       VARCHAR2 DEFAULT 'INFO'
    );

    PROCEDURE log_msg(p_message VARCHAR2);
    PROCEDURE log_variable(p_name VARCHAR2, p_value VARCHAR2);
    PROCEDURE log_error(p_proc VARCHAR2, p_err VARCHAR2);
END debug_utils;
/


CREATE OR REPLACE PACKAGE BODY debug_utils AS

    g_debug_enabled BOOLEAN := FALSE;
    g_info_enabled  BOOLEAN := TRUE;
    g_warn_enabled  BOOLEAN := TRUE;
    g_error_enabled BOOLEAN := TRUE;

    PROCEDURE enable_debug IS
    BEGIN
        g_debug_mode := TRUE;
        g_debug_enabled := TRUE;
        g_info_enabled := TRUE;
        g_warn_enabled := TRUE;
        g_error_enabled := TRUE;
    END enable_debug;


    PROCEDURE disable_debug IS
    BEGIN
        g_debug_mode := FALSE;
    END disable_debug;


    PROCEDURE enable_level(p_level VARCHAR2) IS
        v_level VARCHAR2(10) := UPPER(p_level);
    BEGIN
        g_debug_mode := TRUE;

        CASE v_level
            WHEN 'DEBUG' THEN g_debug_enabled := TRUE;
            WHEN 'INFO'  THEN g_info_enabled := TRUE;
            WHEN 'WARN'  THEN g_warn_enabled := TRUE;
            WHEN 'ERROR' THEN g_error_enabled := TRUE;
            ELSE
                RAISE_APPLICATION_ERROR(-20001, 'Invalid log level: ' || UPPER(p_level));
        END CASE;
    END enable_level;


    PROCEDURE disable_level(p_level VARCHAR2) IS
        v_level VARCHAR2(10) := UPPER(p_level);
    BEGIN
        CASE v_level
            WHEN 'DEBUG' THEN g_debug_enabled := FALSE;
            WHEN 'INFO'  THEN g_info_enabled := FALSE;
            WHEN 'WARN'  THEN g_warn_enabled := FALSE;
            WHEN 'ERROR' THEN g_error_enabled := FALSE;
            ELSE
                RAISE_APPLICATION_ERROR(-20001, 'Invalid log level: ' || v_level);
        END CASE;
    END disable_level;


    PROCEDURE log(
        p_module_name VARCHAR2,
        p_line        NUMBER,
        p_message     VARCHAR2,
        p_level       VARCHAR2 DEFAULT 'INFO'
    ) IS
        v_level   VARCHAR2(10) := UPPER(NVL(p_level, 'INFO'));
        v_enabled BOOLEAN := FALSE;
    BEGIN
        CASE v_level
            WHEN 'DEBUG' THEN v_enabled := g_debug_enabled;
            WHEN 'INFO'  THEN v_enabled := g_info_enabled;
            WHEN 'WARN'  THEN v_enabled := g_warn_enabled;
            WHEN 'ERROR' THEN v_enabled := g_error_enabled;
            ELSE
                RAISE_APPLICATION_ERROR(-20001, 'Invalid log level: ' || v_level);
        END CASE;

        IF g_debug_mode AND v_enabled THEN
            INSERT INTO debug_log (
                module_name,
                line_no,
                log_level,
                log_message
            )
            VALUES (
                p_module_name,
                p_line,
                v_level,
                p_message
            );
        END IF;
    END log;


    PROCEDURE log_msg(p_message VARCHAR2) IS
    BEGIN
        log('MESSAGE', NULL, p_message, 'INFO');
    END log_msg;


    PROCEDURE log_variable(p_name VARCHAR2, p_value VARCHAR2) IS
    BEGIN
        log('VARIABLE', NULL, p_name || ' = ' || NVL(p_value, 'NULL'), 'DEBUG');
    END log_variable;


    PROCEDURE log_error(p_proc VARCHAR2, p_err VARCHAR2) IS
    BEGIN
        log(p_proc, NULL, 'ERROR: ' || p_err, 'ERROR');
    END log_error;

END debug_utils;
/

---------------------------------------------------------------------------------
---------------------------- PART II ---------------------------------------------
---------------------------------------------------------------------------------


CREATE TABLE employees (
    employee_id    NUMBER PRIMARY KEY,
    full_name      VARCHAR2(100) NOT NULL,
    salary         NUMBER(10, 2) NOT NULL,
    commission_pct NUMBER(5, 4)
     CHECK (commission_pct BETWEEN 0 AND 1) -- let's say we can't offer more than double the salary
);

-- some data
INSERT INTO employees VALUES (1, 'Ana Pop', 5000, 0.10);
INSERT INTO employees VALUES (2, 'Mihai Ionescu', 4500, NULL);
INSERT INTO employees VALUES (3, 'Elena Stan', 6000, 0.05);
INSERT INTO employees VALUES(4, 'Florian Popescu', 10000, 0.4);

COMMIT;

CREATE OR REPLACE PROCEDURE adjust_salaries_by_commission IS

    CURSOR employee_cursor IS
        SELECT employee_id, full_name, salary, commission_pct
        FROM employees
        ORDER BY employee_id;
    v_increase NUMBER;
BEGIN
    debug_utils.log( $$PLSQL_UNIT,  $$PLSQL_LINE, 'Procedure started');

    -- go through all employees
    FOR employee_row IN employee_cursor LOOP

        debug_utils.log( $$PLSQL_UNIT,  $$PLSQL_LINE, 'Reading employee: ' || employee_row.full_name);

        IF employee_row.commission_pct IS NULL THEN
            debug_utils.log($$PLSQL_UNIT, $$PLSQL_LINE, 'Commission is NULL; using the default rate of 2%', 'WARN');
        END IF;
    

        debug_utils.log_msg('testtttttttttttttttttttttttttttttttt');
        debug_utils.log_msg('testtttttttttttttttttttttttttttttttt');
        debug_utils.log_msg('testtttttttttttttttttttttttttttttttt');

        v_increase := employee_row.salary * NVL(employee_row.commission_pct, 0.02);

        debug_utils.log_variable('salary increase',TO_CHAR(v_increase));

        UPDATE employees
        SET salary = salary + v_increase
        WHERE employee_id = employee_row.employee_id;

        debug_utils.log($$PLSQL_UNIT, $$PLSQL_LINE, 'Salary updated for: ' || employee_row.full_name);
    END LOOP;

    debug_utils.log('ADJUST_SALARIES_BY_COMMISSION',  $$PLSQL_LINE, 'Procedure finished', 'INFO');

    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        debug_utils.log_error( $$PLSQL_UNIT, SQLERRM);
        RAISE;
END adjust_salaries_by_commission;
/
